version: '2'

services:
#  mysql:
#   image: mysql:5.7
#   container_name: szsx-mysql
#   restart: always
#   ports:
#     - "3306:3306"
#   volumes:
#     - ./shop-data/mysql/data:/var/lib/mysql
#   environment:
#     - "MYSQL_ROOT_PASSWORD=facemeng123"
#     - "MYSQL_DATABASE=school"
#   command:
#      ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  shop-redis:
    image: redis:5
    container_name: shop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./shop-data/redis/data:/data
    command:
      ["redis-server", "--requirepass", "facemeng123", "--appendonly", "yes"]


#  shop-eureka:
#    image: 180.117.163.162:15580/shop-cloud/shop-eureka
#    hostname: shop-eureka
#    container_name: shop-eureka
#    ports:
#      - "8000:9000"
#    command: --spring.profiles.active=dev
#  shop-zuul:
#    image: 180.117.163.162:15580/shop-cloud/shop-zuul
#    hostname: shop-zuul
#    container_name: shop-zuul
#    ports:
#      - "8010:9010"
#    command: --spring.profiles.active=dev
#    depends_on:
#      - shop-eureka
#      - shop-user-service
#      - shop-order-service
#  shop-user-service:
#    image: 180.117.163.162:15580/shop-cloud/user-core
#    hostname: shop-user-service
#    container_name: shop-user-service
##    ports:
##      - "9020:9020"
#    command: --spring.profiles.active=dev
#    depends_on:
#      - shop-eureka
#  shop-order-service:
#    image: 180.117.163.162:15580/shop-cloud/order-core
#    hostname: shop-order-service
#    container_name: shop-order-service
##    ports:
##      - "9030:9030"
#    command: --spring.profiles.active=dev
#    depends_on:
#      - shop-eureka

