version: '2'

services:
  shop-mysql:
    image: mysql:5.7
    container_name: shop-mysql
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./shop-data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=facemeng123
      - MYSQL_DATABASE=shop
    command:
      ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    networks:
      shop:
        ipv4_address: 172.32.16.120

  shop-redis:
    image: redis:5
    container_name: shop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./shop-data/redis/data:/data
    command:
      ["redis-server", "--requirepass", "facemeng123", "--appendonly", "yes"]
    networks:
      shop:
        ipv4_address: 172.32.16.130

  shop-rabbitmq:
    image: suanmilk/rabbitmq-delay:3.7
    hostname: shop-rabbitmq
    container_name: shop-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=facemeng123"
      - "RABBITMQ_DEFAULT_VHOST=shop"
    volumes:
      - ./shop-data/rabbitmq/data:/var/lib/rabbitmq
    networks:
      shop:
        ipv4_address: 172.32.16.140

networks:
  shop:
    driver: bridge
    ipam:
      config:
      - subnet: 172.32.16.0/24
        gateway: 172.32.16.1