spring:
  profiles:
    # 默认的profile为local，其他环境通过指定启动参数使用不同的profile，比如：
    # 生产环境：java -jar xxx.jar --spring.profiles.active=dev
    active: local
  security:
    user:
      name: wp                # 配置登录的账号是facemeng
      password: wp123     # 配置登录的密码是facemeng123
server:
  port: 8000