server:
  # 指定Tomcat端口
  port: 8030
spring:
  profiles:
    # 默认的profile为local，其他环境通过指定启动参数使用不同的profile，比如：
    # 生产环境：java -jar xxx.jar --spring.profiles.active=dev
    active: local
#management:
#  endpoint:
#    health:
#      # 是否展示健康检查详情
#      show-details: always