eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://wp:wp123@localhost:8000/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

spring:
  redis:
    host: localhost
    password: facemeng123
    port: 6379
    timeout: 1000ms #超时时间
    database: 0 #0-15 16个库 默认0
    lettuce:
      pool:
        max-active: 32 #最大连接数
        max-wait: 1000ms #默认-1 最大连接阻塞等待时间
        max-idle: 32 #最大空闲连接 默认8
        min-idle: 8 #最小空闲连接
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: facemeng123
    virtual-host: /shop

logging:
  level:
    com.wp.cloud.shop: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    com.netflix: DEBUG