eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://wp:wp123@localhost:8000/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

logging:
  level:
    com.wp.cloud.shop: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    com.netflix: DEBUG