spring:
  zipkin:
    sender:
      type: kafka
    service:
      name: ${spring.application.name} #zipkin里看到的的service name
  sleuth:
    sampler:
      probability: 1.0 #将采样比例1.0是全部都采集，默认是0.1
  kafka:
    bootstrap-servers: 192.168.0.151:9092,192.168.0.152:9092,192.168.0.153:9092 #集群的情况直接用“,”分割
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://wp:wp123@shop-eureka:9000/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
#  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0       # 重试相同实例
  MaxAutoRetriesNextServer: 0 # 重试下一实例
  okhttp:
    enabled: true

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #是否开启超时熔断
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 15000 #断路器超时时间，默认1000ms

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always

logging:
  level:
    com.wp.cloud.shop: DEBUG
#    com.netflix: DEBUG