server:
  port: 8010
spring:
  profiles:
    # 默认的profile为local，其他环境通过指定启动参数使用不同的profile，比如：
    # 生产环境：java -jar xxx.jar --spring.profiles.active=dev
    active: local

zuul:
#  retryable: true         # 全局设置，默认不开启重试机制
  ignored-services: '*'   # 使用'*'可忽略所有微服务
  prefix: /api            # 请求路径前缀
#  strip-prefix: false     # 请求路径是否包含前缀
  routes:
    shop-order-service:            # 该配置方式中，buy-route只是给路由一个名称，可以任意起名。
      service-id: shop-order-service
      path: /shop-order/**
    shop-user-service:           # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
      service-id: shop-user-service
      path: /shop-user/**
    shop-file-service:           # 该配置方式中，user-route只是给路由一个名称，可以任意起名。
      service-id: shop-file-service
      path: /shop-file/**
#      retryable: true     # 默认不开启重试机制
#  ignoredPatterns: /**/admin/**   # 忽略所有包含/admin/的路径